import type { ThemeTokens } from "@/types/gift";

/**
 * Centralized theme tokens (spec section 49). Each theme changes background,
 * gradients, typography pairing, particle style, card style, and animation
 * personality together — never just a single accent color — so the recipient
 * experience feels genuinely different theme to theme.
 *
 * Consumers should apply a theme by setting `data-theme={id}` on the root
 * element; see app/globals.css for the CSS custom-property bindings. The
 * `emoji` + `moodDescription` pair is purely for the creator-facing theme
 * picker card (spec: emoji/icon-led selection instead of a raw color swatch).
 */
export const THEMES: ThemeTokens[] = [
  {
    id: "classic",
    name: "Classic",
    // Not a cake — this theme is shared by every occasion (anniversaries,
    // proposals, apologies...), not just birthdays, so a birthday-specific
    // glyph here read as a mismatched/wrong icon on non-birthday gifts.
    emoji: "🌟",
    moodDescription: "Warm and timeless — a classic celebration feel.",
    group: "classic",
    background: "#FFF9F5",
    surface: "#FFFFFF",
    primary: "#E85C7B",
    secondary: "#F7B267",
    text: "#2B2320",
    accent: "#E85C7B",
    particleStyle: "none",
    buttonStyle: "rounded",
    cardStyle: "solid",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "soft",
    previewGradient: "linear-gradient(135deg,#FFF9F5,#F7B267,#E85C7B)",
  },
  {
    id: "galaxy",
    name: "Galaxy",
    emoji: "🌌",
    moodDescription: "Dreamy stars and cosmic wonder.",
    group: "elegant",
    background: "#0B0B24",
    surface: "#15163B",
    primary: "#8A5CFF",
    secondary: "#4FD1FF",
    text: "#F1EEFF",
    accent: "#B993FF",
    particleStyle: "stars",
    buttonStyle: "pill",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "cinematic",
    previewGradient: "linear-gradient(135deg,#0B0B24,#4527A0,#4FD1FF)",
  },
  {
    id: "emerald",
    name: "Emerald",
    emoji: "💎",
    moodDescription: "Rich, elegant, and full of grace.",
    group: "elegant",
    background: "#062A24",
    surface: "#0C3B32",
    primary: "#2ED9A3",
    secondary: "#C9A75E",
    text: "#EAFBF5",
    accent: "#2ED9A3",
    particleStyle: "sparkle",
    buttonStyle: "sharp",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "dreamy",
    previewGradient: "linear-gradient(135deg,#062A24,#0C3B32,#2ED9A3)",
  },
  {
    id: "frost",
    name: "Frost",
    emoji: "❄️",
    moodDescription: "Cool, crisp, and softly magical.",
    group: "classic",
    background: "#EAF6FB",
    surface: "#FFFFFF",
    primary: "#4CA8D9",
    secondary: "#BFE9F5",
    text: "#183642",
    accent: "#4CA8D9",
    particleStyle: "snow",
    buttonStyle: "rounded",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "dreamy",
    previewGradient: "linear-gradient(135deg,#EAF6FB,#BFE9F5,#4CA8D9)",
  },
  {
    id: "midnight",
    name: "Midnight",
    emoji: "🌙",
    moodDescription: "Deep midnight blues with a calm shine.",
    group: "elegant",
    background: "#0A0E1A",
    surface: "#131A2E",
    primary: "#5C7CFA",
    secondary: "#F5A623",
    text: "#E7EAF6",
    accent: "#5C7CFA",
    particleStyle: "stars",
    buttonStyle: "sharp",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "cinematic",
    previewGradient: "linear-gradient(135deg,#0A0E1A,#131A2E,#5C7CFA)",
  },
  {
    id: "party",
    name: "Party",
    emoji: "🎉",
    moodDescription: "Bright, playful, and full of energy.",
    group: "festive",
    background: "#FFF4E0",
    surface: "#FFFFFF",
    primary: "#FF5D8F",
    secondary: "#5CD0FF",
    text: "#2B1E1E",
    accent: "#FFC93C",
    particleStyle: "confetti",
    buttonStyle: "pill",
    cardStyle: "solid",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "energetic",
    previewGradient: "linear-gradient(135deg,#FF5D8F,#FFC93C,#5CD0FF)",
  },
  {
    id: "floating-hearts",
    name: "Floating Hearts",
    emoji: "💗",
    moodDescription: "Soft pinks drifting with love.",
    group: "romantic",
    background: "#FFF0F5",
    surface: "#FFFFFF",
    primary: "#FF6FA5",
    secondary: "#FFB4C6",
    text: "#3B1D28",
    accent: "#FF6FA5",
    particleStyle: "hearts",
    buttonStyle: "pill",
    cardStyle: "solid",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "dreamy",
    previewGradient: "linear-gradient(135deg,#FFF0F5,#FFB4C6,#FF6FA5)",
  },
  {
    id: "neon-hearts",
    name: "Neon Hearts",
    emoji: "💖",
    moodDescription: "Electric romance that glows in the dark.",
    group: "romantic",
    background: "#12081A",
    surface: "#1E0F2E",
    primary: "#FF2E9F",
    secondary: "#00E5FF",
    text: "#FBEBFF",
    accent: "#FF2E9F",
    particleStyle: "hearts",
    buttonStyle: "pill",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "energetic",
    previewGradient: "linear-gradient(135deg,#12081A,#FF2E9F,#00E5FF)",
  },
  {
    id: "sparkle-hearts",
    name: "Sparkle Hearts",
    emoji: "✨",
    moodDescription: "Sparkling and sweet, made for love.",
    group: "romantic",
    background: "#FFF5FA",
    surface: "#FFFFFF",
    primary: "#E0559A",
    secondary: "#FFD966",
    text: "#3A1F2E",
    accent: "#E0559A",
    particleStyle: "sparkle",
    buttonStyle: "rounded",
    cardStyle: "solid",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "dreamy",
    previewGradient: "linear-gradient(135deg,#FFF5FA,#FFD966,#E0559A)",
  },
  {
    id: "two-hearts",
    name: "Two Hearts",
    emoji: "💞",
    moodDescription: "Two hearts, one gentle story.",
    group: "romantic",
    background: "#FFF1F0",
    surface: "#FFFFFF",
    primary: "#D94F5C",
    secondary: "#F2A6A0",
    text: "#331313",
    accent: "#D94F5C",
    particleStyle: "hearts",
    buttonStyle: "rounded",
    cardStyle: "paper",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "soft",
    previewGradient: "linear-gradient(135deg,#FFF1F0,#F2A6A0,#D94F5C)",
  },
  {
    id: "romantic-sunset",
    name: "Romantic Sunset",
    emoji: "🌇",
    moodDescription: "A warm sunset wrapped in romance.",
    group: "romantic",
    background: "#2A1030",
    surface: "#3A1740",
    primary: "#FF7E5F",
    secondary: "#FEB47B",
    text: "#FFEFE5",
    accent: "#FF7E5F",
    particleStyle: "sparkle",
    buttonStyle: "pill",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "cinematic",
    previewGradient: "linear-gradient(135deg,#2A1030,#FF7E5F,#FEB47B)",
  },
  {
    id: "starlight-love",
    name: "Starlight Love",
    emoji: "🌠",
    moodDescription: "Starlit skies for a dreamy love story.",
    group: "romantic",
    background: "#0C1130",
    surface: "#171C45",
    primary: "#FFD1E8",
    secondary: "#8FA6FF",
    text: "#F3F4FF",
    accent: "#FFD1E8",
    particleStyle: "stars",
    buttonStyle: "pill",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "cinematic",
    previewGradient: "linear-gradient(135deg,#0C1130,#8FA6FF,#FFD1E8)",
  },
  {
    id: "classic-gold",
    name: "Classic Gold",
    emoji: "🏆",
    moodDescription: "Timeless gold for an elegant celebration.",
    group: "elegant",
    background: "#1A140A",
    surface: "#241D10",
    primary: "#D4AF37",
    secondary: "#F5E7C1",
    text: "#FBF3DF",
    accent: "#D4AF37",
    particleStyle: "sparkle",
    buttonStyle: "sharp",
    cardStyle: "solid",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "cinematic",
    previewGradient: "linear-gradient(135deg,#1A140A,#D4AF37,#F5E7C1)",
  },
  {
    id: "galaxy-violet",
    name: "Galaxy Violet",
    emoji: "🔮",
    moodDescription: "Violet galaxies and mysterious wonder.",
    group: "elegant",
    background: "#180B2E",
    surface: "#241340",
    primary: "#B15CFF",
    secondary: "#5CE1FF",
    text: "#F2E9FF",
    accent: "#B15CFF",
    particleStyle: "stars",
    buttonStyle: "pill",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "cinematic",
    previewGradient: "linear-gradient(135deg,#180B2E,#B15CFF,#5CE1FF)",
  },
  {
    id: "emerald-teal",
    name: "Emerald Teal",
    emoji: "🌿",
    moodDescription: "Cool teals with quiet elegance.",
    group: "elegant",
    background: "#04211D",
    surface: "#0A302B",
    primary: "#2FD8C6",
    secondary: "#9AF0E4",
    text: "#E4FBF7",
    accent: "#2FD8C6",
    particleStyle: "sparkle",
    buttonStyle: "rounded",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "dreamy",
    previewGradient: "linear-gradient(135deg,#04211D,#0A302B,#2FD8C6)",
  },
  {
    id: "frost-crystal",
    name: "Frost Crystal",
    emoji: "🧊",
    moodDescription: "Crystal-clear and gently radiant.",
    group: "elegant",
    background: "#EFF7FB",
    surface: "#FFFFFF",
    primary: "#7FB8D9",
    secondary: "#D6E9F5",
    text: "#122A36",
    accent: "#7FB8D9",
    particleStyle: "snow",
    buttonStyle: "rounded",
    cardStyle: "glass",
    fontDisplay: "var(--font-display)",
    fontBody: "var(--font-body)",
    animationStyle: "dreamy",
    previewGradient: "linear-gradient(135deg,#EFF7FB,#D6E9F5,#7FB8D9)",
  },
];

export const DEFAULT_THEME_ID = "floating-hearts";

export function getTheme(id: string): ThemeTokens {
  return THEMES.find((t) => t.id === id) ?? THEMES.find((t) => t.id === DEFAULT_THEME_ID)!;
}
